"""
Django settings for store project.

Generated by 'django-admin startproject' using Django 5.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""
import sys

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-qlw05vrtxvg+v9_tdyfhb7!vka&tn8#+te$a&5*_qml#12al6z'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']

DOMAIN_NAME = 'http://localhost:8000'

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',
    'django.contrib.humanize',

    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.github',

    'debug_toolbar',

    'products',
    'orders',
    'users',
]

MIDDLEWARE = [
    "debug_toolbar.middleware.DebugToolbarMiddleware",  # ДОЛЖНО БЫТЬ ЗДЕСЬ!
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "allauth.account.middleware.AccountMiddleware",
]

ROOT_URLCONF = 'store.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'products.context_processors.baskets',
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                # 'users.context_processors.social_apps_available'
            ],
        },
    },
]

WSGI_APPLICATION = 'store.wsgi.application'


INTERNAL_IPS = [
    '127.0.0.1',
    'localhost',
]


CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": "redis://127.0.0.1:6379/0",
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
        }
    }
}




# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': 'store1_db',
        'USER': 'store1_username',
        'PASSWORD': 'store_password',
        'HOST':  'localhost',
        'PORT': '5432'
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATICFILES_DIRS = (BASE_DIR / 'static',)  # ищет путь до директории со статикой

STATIC_URL = '/static/'  # определяет путь до статики в браузере

STATIC_ROOT = BASE_DIR / 'staticfiles' # для collectstatic

MEDIA_URL = '/media/'

MEDIA_ROOT = BASE_DIR / 'media'


# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Users

AUTH_USER_MODEL = 'users.User'
LOGIN_URL = 'users:login'
LOGIN_REDIRECT_URL = 'index'
LOGOUT_REDIRECT_URL = 'index'


# Sending emails

EMAIL_HOST = 'smtp.yandex.com'
EMAIL_PORT = 465
EMAIL_HOST_USER = 'ronaldoalmeyda@ya.ru'
EMAIL_HOST_PASSWORD = 'yxinmtqcohjarcyb'
EMAIL_USE_SSL = True
# EMAIL_BACKEND = 'django.core.mail.bakcend.console.EmailBackend'


# OAuth

AUTHENTICATION_BACKENDS = [

    # Needed to login by username in Django admin, regardless of `allauth`
    'django.contrib.auth.backends.ModelBackend',

    # `allauth` specific authentication methods, such as login by email
    'allauth.account.auth_backends.AuthenticationBackend',

]


SITE_ID = 2

SOCIALACCOUNT_PROVIDERS = {
    'github': {
        'SCOPE': [
            'user',
        ],
    }
}


# Celery

CELERY_BROKER_URL = 'redis://127.0.0.1:6379/0'
CELERY_RESULT_BACKEND = 'redis://127.0.0.1:6379/0'


CELERY_TASK_ALWAYS_EAGER = "test" in sys.argv

# Stripe

STRIPE_SECRET_KEY = 'sk_test_51R9tnNPvnNHh3SIebfoiCGx8S0VDAeeljSBD7nWhYFmUfmvvMhp3QzL0VN6hsJfysKfnoP20uYwuJ3wEMMlTUhor00dOC0QVll'
STRIPE_PUBLIC_KEY = 'pk_test_51R9tnNPvnNHh3SIegwYU6tgdzGl9hoCXExk4QHlsS7CEnq1c3jOGjpoyGfpZAVaRw3kAz9jRHkk6jGwmFBWc5Mrj00eC4QQNeG'
STRIPE_WEBHOOK_SECRET = 'whsec_d290d368c55d97777d48108f378353058ea8afbbeecc2f6d74b049adae37e597'

# nobly-holy-upbeat-exalt

# The Stripe CLI is configured for New business sandbox with account id acct_1R9tnNPvnNHh3SIe
